import math
class Application:
    def add(self,a,b):
        return 0
    def sub(self,a,b):
        return 0
    def mul(self,a,b):
        return 0
    def div(self,a,b):
        return 0
    def sqrt(self,val):
        return 0
    def log(self,val):
        return 0
    def exp(self,base,power):
        return 0
